# Generated by Django 4.1.4 on 2023-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_kirrurl_active_alter_kirrurl_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kirrurl",
            name="shortcode",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
