# Generated by Django 4.1.4 on 2023-01-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_kirrurl_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kirrurl",
            name="shortcode",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
