# Generated by Django 4.1.4 on 2023-01-31 03:48

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_alter_kirrurl_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kirrurl",
            name="url",
            field=models.CharField(
                max_length=220,
                validators=[
                    shortener.validators.validate_url,
                    shortener.validators.validate_dot_com,
                ],
            ),
        ),
    ]
